/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App1 {
    public String getGreeting() {
        return "mhess-swl thinks he owns App1, but he doesn't";
    }

    public static void main(String[] args) {
        System.out.println(new App1().getGreeting());
    }
}
