/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App3 {
    public String getGreeting() {
        return "App3";
    }

    public static void main(String[] args) {
        System.out.println(new App3().getGreeting());
    }
}
