/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App4 {
    public String getGreeting() {
        return "jeffrey-morgan34 owns App4";
    }

    public static void main(String[] args) {
        System.out.println(new App4().getGreeting());
    }
}
