/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class AppAll {
    public String getGreeting() {
        return "AppAll";
    }

	private String getName() {
		return "AppAll";
	}

    public static void main(String[] args) {
        System.out.println(new AppAll().getGreeting());
    }

	private String override1() {
		return getName() + "-override1";
	}
}
