/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App1 classUnderTest = new App1();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
